name: counter
version: 1.0.0
summary: Flutter Demo Simple Counter Application
description: A demo of Simple Counter Application using Flutter
confinement: strict
base: core18
grade: stable
icon: snap/gui/icon.png


apps:
   counter:
     command: counter
     extensions: [flutter-master]
     plugs:
       - network
       - desktop

parts:
  counter:
    source: .
    plugin: nil
    build-snaps: 
     - flutter/latest/stable

architectures:
  - build-on: amd64
    run-on: arm64
