name: simple-counter
version: 1.0.0
summary: Flutter Demo Simple Counter Application
description: A demo of Simple Counter Application using Flutter
confinement: strict
base: core22
grade: stable
icon: snap/gui/icon.png


apps:
   counter:
     command: simple-counter
    #  extensions: [flutter-master]
     plugs:
       - network
       - desktop

parts:
  counter:
    source: .
    plugin: nil
    build-snaps: 
     - flutter/latest/stable
    flutter-target: lib/main.dart # The main entry-point file of the application

architectures:
  - build-on: amd64
    run-on: arm64
